#!/bin/bash

echo "================================"
echo " Finding all Cloud Credentials"

# get list
for SECRET_NAME in $(kubectl get secret -n cattle-global-data -l cattle.io/creator=norman --no-headers -o custom-columns=:metadata.name)
do
    NAME=$(kubectl get secret -n cattle-global-data $SECRET_NAME -o jsonpath='{.metadata.annotations.field\.cattle\.io/name}')
    echo "$NAME == $SECRET_NAME"
done
echo "================================"
