cloudprovider: amazonec2
cloudCredentialSecretName: cattle-global-data:cc-ccjch
cluster:
  annotations: {}
  labels:
    environment: cloud
    cluster_name: omega
  name: rke2-aws-cloud-omega
kubernetesVersion: v1.24.2+rke2r1
monitoring:
  enabled: false
rke:
  localClusterAuthEndpoint:
    enabled: false
nodepools:
- etcd: true
  controlplane: true
  worker: false
  displayName: control-plane-a
  labels: {}
  taints: {}
  quantity: 1
  paused: false
  name: control-plane-a
  ami: ami-0f1289f37e46c1eff
  deviceName: /dev/sda1
  encryptEbsVolume: false
  endpoint: ""
  iamInstanceProfile: K8sUnrestrictedCloudProviderRole
  insecureTransport: false
  instanceType: t3a.xlarge
  region: us-gov-west-1
  createSecurityGroup: true
  securityGroups: []
  keypairName: ""
  securityGroupReadonly: false
  sshKeyContents: ""
  subnetId: subnet-0d0cd26cf51719ef2
  monitoring: false
  openPort:
  - "8080"
  - "8443"
  - "443"
  privateAddressOnly: false
  requestSpotInstance: false
  tags: owner,brian,KeepRunning,true,changed,true
  retries: 5
  rootSize: 20
  sshUser: ubuntu
  volumeType: gp2
  vpcId: vpc-06a1e85ad08595b21
  useEbsOptimizedInstance: false
  usePrivateAddress: false
  userdata: ""
  zone: a
- etcd: false
  controlplane: false
  worker: true
  displayName: worker-a
  labels: {}
  taints: {}
  quantity: 1
  paused: false
  name: worker-a
  ami: ami-0f1289f37e46c1eff
  deviceName: /dev/sda1
  encryptEbsVolume: false
  endpoint: ""
  iamInstanceProfile: K8sUnrestrictedCloudProviderRole
  insecureTransport: false
  instanceType: c5a.xlarge
  region: us-gov-west-1
  createSecurityGroup: true
  securityGroups: []
  keypairName: ""
  securityGroupReadonly: false
  sshKeyContents: ""
  subnetId: subnet-0d0cd26cf51719ef2
  monitoring: false
  openPort:
  - "8080"
  - "8443"
  - "443"
  privateAddressOnly: false
  requestSpotInstance: false
  tags: owner,brian,KeepRunning,true
  retries: 5
  rootSize: 20
  sshUser: ubuntu
  volumeType: gp2
  vpcId: vpc-06a1e85ad08595b21
  useEbsOptimizedInstance: false
  usePrivateAddress: false
  userdata: ""
  zone: a
- etcd: false
  controlplane: false
  worker: true
  displayName: worker-b
  labels: {}
  taints: {}
  quantity: 1
  paused: false
  name: worker-b
  ami: ami-0f1289f37e46c1eff
  deviceName: /dev/sda1
  encryptEbsVolume: false
  endpoint: ""
  iamInstanceProfile: K8sUnrestrictedCloudProviderRole
  insecureTransport: false
  instanceType: c5a.xlarge
  region: us-gov-west-1
  createSecurityGroup: true
  securityGroups: []
  keypairName: ""
  securityGroupReadonly: false
  sshKeyContents: ""
  subnetId: subnet-09bd4e09215b4f39f
  monitoring: false
  openPort:
  - "8080"
  - "8443"
  - "443"
  privateAddressOnly: false
  requestSpotInstance: false
  tags: owner,brian,KeepRunning,true
  retries: 5
  rootSize: 20
  sshUser: ubuntu
  volumeType: gp2
  vpcId: vpc-06a1e85ad08595b21
  useEbsOptimizedInstance: false
  usePrivateAddress: false
  userdata: ""
  zone: b
- etcd: false
  controlplane: false
  worker: true
  displayName: worker-c
  labels: {}
  taints: {}
  quantity: 1
  paused: false
  name: worker-c
  ami: ami-0f1289f37e46c1eff
  deviceName: /dev/sda1
  encryptEbsVolume: false
  endpoint: ""
  iamInstanceProfile: K8sUnrestrictedCloudProviderRole
  insecureTransport: false
  instanceType: c5a.xlarge
  region: us-gov-west-1
  createSecurityGroup: true
  securityGroups: []
  keypairName: ""
  securityGroupReadonly: false
  sshKeyContents: ""
  subnetId: subnet-0116d99e8f363e0cb
  monitoring: false
  openPort:
  - "8080"
  - "8443"
  - "443"
  privateAddressOnly: false
  requestSpotInstance: false
  tags: owner,brian,KeepRunning,true
  retries: 5
  rootSize: 20
  sshUser: ubuntu
  volumeType: gp2
  vpcId: vpc-06a1e85ad08595b21
  useEbsOptimizedInstance: false
  usePrivateAddress: false
  userdata: ""
  zone: c
